services:
  dronemap:
    image: vimodev/dronemap:latest
    ports:
      - "3333:3333"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_CONNECTION=mysql
      - MYSQL_HOST=dronemap_database
      - MYSQL_PORT=3306
      - MYSQL_USER=dronemap
      - MYSQL_PASSWORD=2024cad0b930c
      - MYSQL_DB_NAME=dronemap
      - TZ=Europe/Amsterdam
    volumes:
      - "/srv/ssdshare/footage_backup:/footage:ro"
    depends_on:
      - dronemap_database
    networks:
      - dronemap-network
          
  dronemap_database:
    image: mariadb:10
    environment:
      - MYSQL_DATABASE=dronemap
      - MYSQL_USER=dronemap
      - MYSQL_PASSWORD=2024cad0b930c
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - TZ=Europe/Amsterdam
    networks:
       - dronemap-network
    ports:
      - "3306:3306"
    restart: unless-stopped

    
networks:
    dronemap-network:
      driver: bridge
      enable_ipv6: false
      ipam:
        driver: default
        config:
          - subnet: 10.10.10.0/24
